package BCE.Localization;

public enum BCEStringId {
  Button_OK(0L),
  Button_Cancel(1L),
  Button_Edit(2L),
  Button_View(3L),
  Button_Delete(4L),
  Button_Preview(5L),
  Button_Print(6L),
  Button_Refresh(7L),
  ErrorConnecting(8L),
  ErrorConnectingSQL2005(9L),
  ErrorSQL2005_10060(10L),
  ErrorSQL2005_10061(11L),
  ErrorSQL2005_10065(12L),
  ErrorSQL2005_1311(13L),
  ErrorSQL2005_1231(14L),
  ErrorSQL2005_11001(15L),
  ErrorSQL2005_10051(16L),
  ErrorConnectionForciblyClosed(17L),
  ErrorGeneralNetwork(18L),
  ErrorTimeoutExpired(19L),
  ErrorLocatingServerOrInstance(20L),
  ErrorTheSpecifiedNetworkNameIsNoLongerAvailable(21L),
  ErrorLoginFailed(22L),
  ErrorCriticalSql(23L),
  ErrorPrimaryKey(24L),
  ErrorForeignKeyMessage(25L),
  ErrorForeignKeyConstraint(26L),
  ErrorDeadLock(27L),
  ErrorUnknownSQLError(28L),
  AccessDenied(29L),
  ContactSystemAdministrator(30L),
  InvalidUserIdOrPassword(31L),
  NewUserAccessDenied(32L),
  Data_NoSQLServer(33L),
  Data_NoSQLDatabaseName(34L),
  BackupRestore_ChangeSQLServer2005LogOnAccountToLocalSystem(35L),
  BackupRestore_UnmatchServerBackupDirectory(36L),
  BackupRestore_UnableToDetermineFileSize(37L),
  BackupRestore_UnknownErrorInCheckingFileExistence(38L),
  BackupRestore_UnableToCreateDirectory(39L),
  BackupRestore_UnauthorizedAccessNetworkFolder(40L),
  BackupRestore_PathTooLong(41L),
  BackupRestore_BackupDirectoryNotFound(42L),
  BackupRestore_IOError(43L),
  BackupRestore_FileNotFound(44L),
  BackupRestore_CopyFileError(45L),
  BackupRestore_NoReadWritePermission(46L),
  BackupRestore_UnableToAccessSharedFolder(47L),
  BackupRestore_IOErrorWhenReadWrite(48L),
  BackupRestore_NoPermissionToDeleteFile(49L),
  BackupRestore_InvalidPath(50L),
  BackupRestore_IOErrorWhenDelete(51L),
  InvalidDDLFile(52L),
  InvalidDDLStatement(53L),
  XtraUtils_AutoWidth(54L),
  XtraUtils_ExportToExcelXls(55L),
  XtraUtils_ExportToExcelXlsx(56L),
  XtraUtils_ExportToRtf(57L),
  XtraUtils_ExportToPdf(58L),
  XtraUtils_ExportToHtml(59L),
  XtraUtils_ExportToText(60L),
  XtraUtils_ExportToXml(61L),
  XtraUtils_PrintGrid(62L),
  XtraUtils_HtmlFiles(63L),
  XtraUtils_ExcelFiles(64L),
  XtraUtils_TextFiles(65L),
  XtraUtils_XmlFiles(66L),
  ConfirmDelete(67L),
  ConfirmCancel(68L),
  ConfirmSaveChanges(69L),
  ThreadForm_Window(70L),
  ThreadForm_SendToBack(71L),
  ThreadForm_WindowList(72L),
  YesNo_Yes(73L),
  YesNo_No(74L),
  CompleteVersion(75L),
  ;
  private long numVal;

  BCEStringId(long numVal) {
    this.numVal = numVal;
  }

  public long getNumVal() {
    return numVal;
  }
}
